"""index telemetry by recorded_at for retention

Revision ID: 15b34d362938
Revises: a63f444bdbbe
Create Date: 2026-09-08 15:15:52.568113
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '15b34d362938'
down_revision: str | None = 'a63f444bdbbe'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_telemetry_recorded', 'telemetry', ['recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_telemetry_recorded', table_name='telemetry')
    # ### end Alembic commands ###
