"""add alerts.clearing_since for alert hysteresis

Revision ID: a63f444bdbbe
Revises: d2d5c8f6a9d2
Create Date: 2026-09-08 15:12:05.309660
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'a63f444bdbbe'
down_revision: str | None = 'd2d5c8f6a9d2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('clearing_since', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'clearing_since')
    # ### end Alembic commands ###
