"""add satellites table and point the operational tables at it

Revision ID: c6dd9ca55c4f
Revises: 15b34d362938
Create Date: 2026-09-10

Written by hand rather than autogenerated: the foreign keys cannot be added
until every `satellite_id` already in the data has a row to point at, and
autogenerate does not know to backfill.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c6dd9ca55c4f"
down_revision: str | None = "15b34d362938"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

REFERRING_TABLES = ("telemetry", "passes", "alerts")


def upgrade() -> None:
    op.create_table(
        "satellites",
        sa.Column("satellite_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("catalog_number", sa.Integer(), nullable=True),
        sa.Column("operator", sa.String(length=128), nullable=True),
        sa.Column("battery_min_v", sa.Float(), nullable=True),
        sa.Column("battery_critical_v", sa.Float(), nullable=True),
        sa.Column("temp_max_c", sa.Float(), nullable=True),
        sa.Column("temp_min_c", sa.Float(), nullable=True),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "catalog_number IS NULL OR catalog_number > 0", name="ck_satellites_catalog"
        ),
        sa.CheckConstraint(
            "battery_critical_v IS NULL OR battery_min_v IS NULL "
            "OR battery_critical_v <= battery_min_v",
            name="ck_satellites_battery_order",
        ),
        sa.CheckConstraint(
            "temp_min_c IS NULL OR temp_max_c IS NULL OR temp_min_c <= temp_max_c",
            name="ck_satellites_temp_order",
        ),
        sa.PrimaryKeyConstraint("satellite_id"),
    )

    # Register every spacecraft the station has already heard from, dating each
    # row from the earliest evidence rather than from the moment of migration.
    op.execute(
        """
        INSERT INTO satellites (satellite_id, name, first_seen_at)
        SELECT satellite_id, satellite_id, MIN(first_seen)
        FROM (
            SELECT satellite_id, MIN(received_at) AS first_seen FROM telemetry
            GROUP BY satellite_id
            UNION ALL
            SELECT satellite_id, MIN(created_at) FROM passes GROUP BY satellite_id
            UNION ALL
            SELECT satellite_id, MIN(detected_at) FROM alerts GROUP BY satellite_id
        ) AS seen
        GROUP BY satellite_id
        ON CONFLICT (satellite_id) DO NOTHING
        """
    )

    for table in REFERRING_TABLES:
        op.create_foreign_key(
            f"fk_{table}_satellite",
            table,
            "satellites",
            ["satellite_id"],
            ["satellite_id"],
            ondelete="RESTRICT",
        )


def downgrade() -> None:
    for table in REFERRING_TABLES:
        op.drop_constraint(f"fk_{table}_satellite", table, type_="foreignkey")
    op.drop_table("satellites")
