"""create passes, telemetry, alerts

Revision ID: d2d5c8f6a9d2
Revises: 
Create Date: 2026-09-07 21:42:28.538419
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'd2d5c8f6a9d2'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('satellite_id', sa.String(length=64), nullable=False),
    sa.Column('ground_station_id', sa.String(length=64), nullable=False),
    sa.Column('aos_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('los_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_elevation_deg', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('frame_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'completed', 'aborted')", name='ck_passes_status'),
    sa.CheckConstraint('los_at IS NULL OR los_at >= aos_at', name='ck_passes_window'),
    sa.CheckConstraint('max_elevation_deg IS NULL OR (max_elevation_deg BETWEEN 0 AND 90)', name='ck_passes_elevation'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_passes_satellite_aos', 'passes', ['satellite_id', sa.literal_column('aos_at DESC')], unique=False)
    op.create_index('uq_passes_open', 'passes', ['satellite_id'], unique=True, postgresql_where=sa.text('los_at IS NULL'))
    op.create_table('telemetry',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('pass_id', sa.BigInteger(), nullable=True),
    sa.Column('satellite_id', sa.String(length=64), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('battery_voltage_v', sa.Float(), nullable=False),
    sa.Column('battery_current_a', sa.Float(), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=False),
    sa.Column('lat_deg', sa.Float(), nullable=False),
    sa.Column('lon_deg', sa.Float(), nullable=False),
    sa.Column('alt_km', sa.Float(), nullable=False),
    sa.Column('signal_strength_dbm', sa.Float(), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('screened_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("mode IN ('NOMINAL', 'SAFE', 'PAYLOAD')", name='ck_telemetry_mode'),
    sa.CheckConstraint('lat_deg BETWEEN -90 AND 90', name='ck_telemetry_lat'),
    sa.CheckConstraint('lon_deg BETWEEN -180 AND 180', name='ck_telemetry_lon'),
    sa.ForeignKeyConstraint(['pass_id'], ['passes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('satellite_id', 'seq', name='uq_telemetry_sat_seq')
    )
    op.create_index('ix_telemetry_pass', 'telemetry', ['pass_id'], unique=False)
    op.create_index('ix_telemetry_sat_recorded', 'telemetry', ['satellite_id', sa.literal_column('recorded_at DESC')], unique=False)
    op.create_index('ix_telemetry_unscreened', 'telemetry', ['id'], unique=False, postgresql_where=sa.text('screened_at IS NULL'))
    op.create_table('alerts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('telemetry_id', sa.BigInteger(), nullable=True),
    sa.Column('pass_id', sa.BigInteger(), nullable=True),
    sa.Column('satellite_id', sa.String(length=64), nullable=False),
    sa.Column('rule', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dedupe_key', sa.String(length=200), nullable=False),
    sa.CheckConstraint("severity IN ('info', 'warning', 'critical')", name='ck_alerts_severity'),
    sa.ForeignKeyConstraint(['pass_id'], ['passes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['telemetry_id'], ['telemetry.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key', name='uq_alerts_dedupe')
    )
    op.create_index('ix_alerts_open', 'alerts', ['satellite_id', sa.literal_column('detected_at DESC')], unique=False, postgresql_where=sa.text('resolved_at IS NULL'))
    op.create_index('ix_alerts_telemetry', 'alerts', ['telemetry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alerts_telemetry', table_name='alerts')
    op.drop_index('ix_alerts_open', table_name='alerts', postgresql_where=sa.text('resolved_at IS NULL'))
    op.drop_table('alerts')
    op.drop_index('ix_telemetry_unscreened', table_name='telemetry', postgresql_where=sa.text('screened_at IS NULL'))
    op.drop_index('ix_telemetry_sat_recorded', table_name='telemetry')
    op.drop_index('ix_telemetry_pass', table_name='telemetry')
    op.drop_table('telemetry')
    op.drop_index('uq_passes_open', table_name='passes', postgresql_where=sa.text('los_at IS NULL'))
    op.drop_index('ix_passes_satellite_aos', table_name='passes')
    op.drop_table('passes')
    # ### end Alembic commands ###
